version: "3"
services:
  backend:
    image: covid-19-xchange_backend
    build:
      context: .
      dockerfile: Dockerfile-backend
    networks:
      portal:
        aliases:
          - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6543/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      - DB_USERNAME={DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    command: make run
    depends_on:
      - mariadb

  wordpress:
    restart: always
    image: covid-19-xchange_wordpress
    build:
      context: .
      dockerfile: Dockerfile-wordpress
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    networks:
      portal:
        aliases:
          - wordpress
    volumes:
    - wordpress-data:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    restart: always
    image: mariadb:10.5.1-bionic
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      portal:
        aliases:
          - mariadb

  nginx:
    restart: always
    image: nginx:1.17.9-alpine
    ports:
      - 443:443
    volumes:
      - ./data/nginx/:/etc/nginx/conf.d
      - letsencrypt-data:/etc/letsencrypt:ro
    networks:
      portal:
        aliases:
          - nginx
    depends_on:
      - wordpress
      - certbot
      #- backend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/dns-route53:v1.3.0
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - letsencrypt-data:/etc/letsencrypt:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot --test-cert renew; sleep 12h & wait $${!}; done;'"

volumes:
  mariadb-data:
  wordpress-data:
  letsencrypt-data:

networks:
  portal:
    driver: bridge
